version: '3'
services:
  easymacher:
    image: easymacher:latest
    environment:
      - EASYMACHER_DB_NAME=${DB_NAME:-easymacher}
      - EASYMACHER_DB_USER=${DB_API_NAME:-doobie}
      - EASYMACHER_DB_PASSWORD=${DB_API_PASSWORD:-123}
      - EASYMACHER_DB_PORT=5432
      - EASYMACHER_DB_ADDRESS=database
    ports:
      - 8080:8080
    networks:
      - network
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_SU_NAME:-postgres}
      - POSTGRES_PASSWORD=${DB_SU_PASSWORD:-1215}
      - POSTGRES_DB=${DB_NAME:-easymacher}
      - EASYMACHER_DB_USER=${DB_API_NAME:-doobie}
      - EASYMACHER_DB_PASSWORD=${DB_API_PASSWORD:-123}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    ports:
      - 5432:5432
networks:
  network:
    driver: bridge