name: easymacher-docker-heroku CD

on:
  push:
    branches: [ auth0-docker-version ]
  pull_request:
    branches: [ auth0-docker-version ]

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  EASYMACHER_DB_NAME: ${{secrets.EASYMACHER_DB_NAME}}
  EASYMACHER_DB_USER: ${{secrets.EASYMACHER_DB_USER}}
  EASYMACHER_DB_PASSWORD: ${{secrets.EASYMACHER_DB_PASSWORD}}
  EASYMACHER_DB_ADDRESS: ${{''}}
  EASYMACHER_DB_PORT: ${{''}}
  APP_NAME: ${{ 'easymacher' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run sbt assembly without tests
        run: sbt "set test in assembly := {}" clean assembly

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Build Docker image
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME